FROM nginx:alpine

# Copy static files directly
COPY . /usr/share/nginx/html

# Copy custom Nginx config (if needed)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]